### ISSUE TITLE
set -> e Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined     at window.<computed>.window.<computed> (C:\mamank\node_modules\@open-wa\wa-automate\dist\lib\launch.js:1:31435)     at __puppeteer_evaluation_script__:3:89     at ExecutionContext._evaluateInternal (C:\mamank\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)     at processTicksAndRejections (internal/process/task_queues.js:93:5)     at async ExecutionContext.evaluate (C:\mamank\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)

### ISSUE THREAD

**Issue by akujeleksad** [ArugaZ/whatsapp-bot#100]
help

**Comment by ArugaZ** [comment]
Make sure all the necessary dependencies are installed: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
