### ISSUE TITLE
kok gini yah ?

### ISSUE THREAD

**Issue by Tanaka9531** [ArugaZ/whatsapp-bot#104]
[EXEC] 27/11/20 21:02:22 klasmen [0] from ㅤ in GRUP
[EROR] TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at HandleMsg (C:\Users\ACER\Arugaz\HandleMsg.js:866:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by mioscape** [comment]
Mungkin belom ada yang badword/belum di aktifin fitur anti badword nya

**Comment by Tanaka9531** [comment]
> Mungkin belom ada yang badword/belum di aktifin fitur anti badword nya

oke makasih saya coba dulu
