### ISSUE TITLE
Error on someone commands

### ISSUE THREAD

**Issue by ferhacks** [ArugaZ/whatsapp-bot#134]
(node:12555) UnhandledPromiseRejectionWarning: Error: Request failed with status code 503
    at createError (/home/colab/whatsapp-bot/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/colab/whatsapp-bot/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/colab/whatsapp-bot/node_modules/axios/lib/adapters/http.js:244:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:12555) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

**Comment by ArugaZ** [comment]
its works now
