### ISSUE TITLE
Help :)

### ISSUE THREAD

**Issue by thoriqazzikra** [ArugaZ/whatsapp-bot#201]
apa cuman ane yg kena error kek gini
jadi kalo option yang ada await aruga.getProfilePicFromServer itu jadi gabisa semua

```TCL: getDUrl -> error TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at dispatchHttpRequest (C:\whatsapp-bot\node_modules\axios\lib\adapters\http.js:66:22)
    at new Promise (<anonymous>)
    at httpAdapter (C:\whatsapp-bot\node_modules\axios\lib\adapters\http.js:21:10)
    at dispatchRequest (C:\whatsapp-bot\node_modules\axios\lib\core\dispatchRequest.js:52:10)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Something went wrong TypeError: Cannot read property 'match' of undefined
    at isDataURL (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:97:235)
    at Client.<anonymous> (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:911:31)
    at step (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:63:23)
    at Object.next (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:44:53)
    at C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:34:12)
    at Client.sendImage (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:906:16)
    at Client.<anonymous> (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:999:33)
    at step (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:63:23)
(node:6344) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at isDataURL (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:97:235)
    at Client.<anonymous> (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:911:31)
    at step (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:63:23)
    at Object.next (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:44:53)
    at C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:34:12)
    at Client.sendImage (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:906:16)
    at Client.<anonymous> (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:999:33)
    at step (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:63:23)
(node:6344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)```

**Comment by Fucksociety666** [comment]
iya sama ,, command !stalkig error gk? pnya gw psti username salah pdhl bener

**Comment by Suryapardana** [comment]
> iya sama ,, command !stalkig error gk? pnya gw psti username salah pdhl bener

Stalkig di gua masih bisa ngab

**Comment by thoriqazzikra** [comment]
> iya sama ,, command !stalkig error gk? pnya gw psti username salah pdhl bener

keknya itu errornya dari server aruga deh, tapi gatau juga
soalnya muncul errornya kalo ada await.arugagetProfilePicFromServer
