### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by JohnCale47** [ArugaZ/whatsapp-bot#241]
SyntaxError: Unexpected token : in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\GitHhh\whatsapp-bot-main\node_modules\@open-wa\wa-automate\dist\controllers\browser.js:186:48)
    at step (C:\GitHhh\whatsapp-bot-main\node_modules\@open-wa\wa-automate\dist\controllers\browser.js:63:23)
    at Object.next (C:\GitHhh\whatsapp-bot-main\node_modules\@open-wa\wa-automate\dist\controllers\browser.js:44:53)
    at fulfilled (C:\GitHhh\whatsapp-bot-main\node_modules\@open-wa\wa-automate\dist\controllers\browser.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by GuckTubeYT** [comment]
Mungkin error nya di json nya
