### ISSUE TITLE
error!!

### ISSUE THREAD

**Issue by Rmdhn-20** [ArugaZ/whatsapp-bot#308]
C:\whatsapp-bot>npm start

> whatsapp-bot@2.1.0 start C:\whatsapp-bot
> node index.js

internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'fluent-ffmpeg'
Require stack:
- C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js
- C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\index.js
- C:\whatsapp-bot\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:96:171)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\whatsapp-bot\\node_modules\\@open-wa\\wa-automate\\dist\\api\\Client.js',
    'C:\\whatsapp-bot\\node_modules\\@open-wa\\wa-automate\\dist\\index.js',
    'C:\\whatsapp-bot\\index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-bot@2.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-bot@2.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-02-10T14_50_18_773Z-debug.log

**Comment by marcos10pc** [comment]
make sure that your installed all modules and try again.

**Comment by Rmdhn-20** [comment]
oke thanks:)
