### ISSUE TITLE
!play error

### ISSUE THREAD

**Issue by muhammadzakizn07** [ArugaZ/whatsapp-bot#56]
(node:7912) UnhandledPromiseRejectionWarning: Error: Request failed with status code 503
    at createError (C:\Users\ACER\WABOT\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\ACER\WABOT\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\ACER\WABOT\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:7912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:7912) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ArugaZ** [comment]
fix
