### ISSUE TITLE
× The session is invalid. Retrying

### ISSUE THREAD

**Issue by ben-dev2609** [ArugaZ/whatsapp-bot#8]
?????????/

**Comment by ArugaZ** [comment]
> ?????????/

scan ulang aja, kl disuruh update ke v3.0.8. klik ctrl+c lalu npm start lgi

**Comment by ben-dev2609** [comment]
> > ?????????/
> 
> scan ulang aja, kl disuruh update ke v3.0.8. klik ctrl+c lalu npm start lgi



udah gw scan 5x lebih tapi session invalid mulu

**Comment by ben-dev2609** [comment]
> > ?????????/
> 
> scan ulang aja, kl disuruh update ke v3.0.8. klik ctrl+c lalu npm start lgi

jadi gw harus gmn bro

**Comment by ArugaZ** [comment]
> > > ?????????/
> > 
> > 
> > scan ulang aja, kl disuruh update ke v3.0.8. klik ctrl+c lalu npm start lgi
> 
> jadi gw harus gmn bro

coba clone ulang bre

**Comment by ben-dev2609** [comment]
> > > > ?????????/
> > > 
> > > 
> > > scan ulang aja, kl disuruh update ke v3.0.8. klik ctrl+c lalu npm start lgi
> > 
> > 
> > jadi gw harus gmn bro
> 
> coba clone ulang bre

× The session is invalid. Retrying
Error: EPERM: operation not permitted, rename 'C:\Users\User\.config\configstore\update-notifier-@open-wa\wa-automate.json.817362713' -> 'C:\Users\User\.config\configstore\update-notifier-@open-wa\wa-automate.json'
    at Object.renameSync (node:fs:772:3)
    at Function.writeFileSync [as sync] (C:\Users\User\whatsapp-bot\node_modules\write-file-atomic\index.js:244:8)
    at Configstore.set all [as all] (C:\Users\User\whatsapp-bot\node_modules\configstore\index.js:61:20)
    at Configstore.delete (C:\Users\User\whatsapp-bot\node_modules\configstore\index.js:101:12)
    at UpdateNotifier.check (C:\Users\User\whatsapp-bot\node_modules\update-notifier\index.js:88:22)
    at module.exports (C:\Users\User\whatsapp-bot\node_modules\update-notifier\index.js:183:17)
    at C:\Users\User\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:97:32
    at step (C:\Users\User\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:63:23)
    at Object.next (C:\Users\User\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:44:53)
    at C:\Users\User\whatsapp-bot\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:38:71 {
  errno: -4048,
  syscall: 'rename',
  code: 'EPERM',
  path: 'C:\\Users\\User\\.config\\configstore\\update-notifier-@open-wa\\wa-automate.json.817362713',
  dest: 'C:\\Users\\User\\.config\\configstore\\update-notifier-@open-wa\\wa-automate.json

**Comment by ben-dev2609** [comment]
dan masih session invalid

**Comment by ArugaZ** [comment]
aduhh tp ane dh coba clone ulang bisa ko

**Comment by ben-dev2609** [comment]
aing dah nyoba trus tapi ga bisa, aing nyoba di vsc tetap ga bisa juga

**Comment by riintan2** [comment]
Bang yg nobg kurang ngerti kok limitnya habis terus
Ubahnya dmna bang

**Comment by ArugaZ** [comment]
> Bang yg nobg kurang ngerti kok limitnya habis terus
> Ubahnya dmna bang

dapatkan api keynya di web http://remove.bg, ubah api key nya di folder settings/api.json
