### ISSUE TITLE
set -> e Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined     at window.<computed>.window.<computed> (C:\sada\node_modules\@open-wa\wa-automate\dist\lib\launch.js:1:31435)     at __puppeteer_evaluation_script__:3:89     at ExecutionContext._evaluateInternal (C:\sada\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)     at processTicksAndRejections (internal/process/task_queues.js:93:5)     at async ExecutionContext.evaluate (C:\sada\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)

### ISSUE THREAD

**Issue by akujeleksad** [ArugaZ/whatsapp-bot#94]
Qr sih muncul tpi di scan ga ada server started gmn nih udh gw tunggu lama ga bisa bisa

**Comment by akujeleksad** [comment]
bantu plis

**Comment by ArugaZ** [comment]
masih gabisa?

**Comment by akujeleksad** [comment]
Belommm lu ga baca wa gua
